### ISSUE TITLE
Trykk og hold på et utklipp for å feste det. Utklipp som ikke er festet, slettes etter én time.

### ISSUE THREAD

**Issue by sindrinj** [SimpleAstronomy/simple-astronomy-lib#14]

**Comment by sindrinj** [comment]
#13

**Comment by sindrinj** [comment]
![Cjxfjzzrzadhbzb8wa%20(1).pdf](https://github.com/SimpleAstronomy/simple-astronomy-lib/files/12239583/Cjxfjzzrzadhbzb8wa.20.1.pdf)

**Comment by damon140** [comment]
For the curiuos, Google Translate says the issue title is Norwegian and translated it to:

> Press and hold a clip to pin it. Unpinned clips are deleted after one hour.
